version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    volumes:
      - ..:/home/ubuntu/workspace:cached
      - ~/.ssh:/home/ubuntu/.ssh:ro
    environment:
      - HOST_UID=${UID:-1000}
      - HOST_GID=${GID:-1000}
      - GITHUB_TOKEN
    command: sleep infinity
    user: ubuntu
